apiVersion: aws.platform.upbound.io/v1alpha1
kind: ControlPlane
metadata:
  name: use1
spec:
  parameters:
    id: use1
    region: us-east-1
    version: "1.34"
    nodes:
      count: 2
      instanceType: t3.large
    accessConfig:
      authenticationMode: API_AND_CONFIG_MAP
      bootstrapClusterCreatorAdminPermissions: true
---
apiVersion: azure.platform.upbound.io/v1alpha1
kind: ControlPlane
metadata:
  name: aze1
spec:
  parameters:
    id: aze1
    location: eastus
    version: "1.34"
    nodes:
      count: 2
      vmSize: Standard_D2s_v3
---
apiVersion: gcp.platform.upbound.io/v1alpha1
kind: ControlPlane
metadata:
  name: gkecp01
spec:
  parameters:
    id: gkecp01
    location: us-central1
    project: crossplane-playground
    version: "1.34"
    nodes:
      count: 2
      machineType: e2-standard-2
